#!/usr/bin/env node
'use strict';

// Generates the Homebrew cask for a Loupe release (Casks/loupe.rb in the
// akshatgg/homebrew-tap repository, which is what makes
// `brew install --cask akshatgg/tap/loupe` work).
//
// Homebrew checks every download against a SHA-256, so the cask must be
// regenerated for each release or `brew install` fails on a checksum
// mismatch. The Release workflow does this automatically; by hand:
//
//   npm run cask:update                          newest release, hashed from GitHub
//   npm run cask:update -- --version 0.2.0       a specific release
//   npm run cask:update -- --dmg-dir dist        hash local DMGs instead
//   ... --out path/to/loupe.rb                   default: dist/loupe.rb

const { createHash } = require('node:crypto');
const fs = require('node:fs');
const path = require('node:path');

const REPO = 'akshatgg/loupe';
const DMGS = { arm: 'Loupe-arm64.dmg', intel: 'Loupe-x64.dmg' };

function renderCask({ version, armSha, intelSha }) {
  for (const [k, v] of Object.entries({ armSha, intelSha })) {
    if (!/^[0-9a-f]{64}$/.test(v)) throw new Error(`${k} is not a SHA-256: ${v}`);
  }
  if (!/^\d+\.\d+\.\d+(-[0-9A-Za-z.-]+)?$/.test(version)) throw new Error(`Bad version: ${version}`);
  return `# Homebrew cask for Loupe -- generated by packaging/update-cask.js in
# github.com/${REPO}; edit that, not this file.
#
# Homebrew ADDS com.apple.quarantine to casks by default. The postflight
# clears it, which is the same permission System Settings -> Privacy &
# Security -> Open Anyway grants by hand: the app is ad-hoc signed, not
# notarized (that needs a paid Apple Developer ID).

cask "loupe" do
  version "${version}"

  on_arm do
    sha256 "${armSha}"
    url "https://github.com/${REPO}/releases/download/v#{version}/${DMGS.arm}"
  end
  on_intel do
    sha256 "${intelSha}"
    url "https://github.com/${REPO}/releases/download/v#{version}/${DMGS.intel}"
  end

  name "Loupe"
  desc "Screen recorder that zooms in while you record"
  homepage "https://loupeapp.vercel.app"

  depends_on macos: :sonoma

  app "Loupe.app"

  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{appdir}/Loupe.app"],
                   must_succeed: false
  end

  uninstall quit: "tech.markai.loupe"

  # Recordings in ~/Movies/Loupe are the user's own files and are left alone.
  zap trash: [
    "~/Library/Application Support/Loupe",
    "~/Library/Preferences/tech.markai.loupe.plist",
    "~/Library/Saved Application State/tech.markai.loupe.savedState",
  ]
end
`;
}

async function sha256OfUrl(url) {
  const res = await fetch(url, { redirect: 'follow' });
  if (!res.ok) throw new Error(`${res.status} fetching ${url}`);
  const hash = createHash('sha256');
  for await (const chunk of res.body) hash.update(chunk);
  return hash.digest('hex');
}

function sha256OfFile(file) {
  return createHash('sha256').update(fs.readFileSync(file)).digest('hex');
}

// Finds a file by name anywhere under dir (actions/download-artifact nests
// each artifact in its own folder).
function findFile(dir, name) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      const found = findFile(p, name);
      if (found) return found;
    } else if (entry.name === name) {
      return p;
    }
  }
  return null;
}

function argValue(args, name) {
  const i = args.indexOf(name);
  return i >= 0 ? args[i + 1] : undefined;
}

async function main(args) {
  const dmgDir = argValue(args, '--dmg-dir');
  const out = argValue(args, '--out') ?? path.join('dist', 'loupe.rb');
  let version = argValue(args, '--version');
  let armSha;
  let intelSha;

  if (dmgDir) {
    if (!version) version = require('../package.json').version;
    const files = Object.values(DMGS).map((n) => findFile(dmgDir, n));
    if (files.includes(null)) throw new Error(`Need ${Object.values(DMGS).join(' and ')} under ${dmgDir}`);
    [armSha, intelSha] = files.map(sha256OfFile);
  } else {
    const which = version ? `tags/v${version}` : 'latest';
    const res = await fetch(`https://api.github.com/repos/${REPO}/releases/${which}`);
    if (!res.ok) throw new Error(`${res.status} fetching release ${which}`);
    const rel = await res.json();
    version = String(rel.tag_name).replace(/^v/, '');
    const url = (name) => {
      const asset = rel.assets.find((a) => a.name === name);
      if (!asset) throw new Error(`Release v${version} has no ${name}`);
      return asset.browser_download_url;
    };
    console.log(`hashing v${version} from GitHub…`);
    [armSha, intelSha] = await Promise.all([sha256OfUrl(url(DMGS.arm)), sha256OfUrl(url(DMGS.intel))]);
  }

  fs.mkdirSync(path.dirname(out), { recursive: true });
  fs.writeFileSync(out, renderCask({ version, armSha, intelSha }));
  console.log(`loupe ${version}\n  arm64 ${armSha}\n  x64   ${intelSha}\nwrote ${out}`);
}

if (require.main === module) {
  main(process.argv.slice(2)).catch((err) => {
    console.error(err.message);
    process.exit(1);
  });
}

module.exports = { renderCask };
